pbrworld.dev/src/BlogBundle/Form/CommentType.php
<?php

namespace BlogBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommentType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('user')
            ->add('comment')
        ;
    }
    
    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'BlogBundle\Entity\Comment'
        ));
    }
	public function getName()
    {
        return 'blogbundle_commenttype';
    }
}

pbrworld.dev/src/BlogBundle/Resources/views/Page/about.html.twig
{% extends 'BlogBundle::layout.html.twig' %}

{% block title %}About{% endblock%}

{% block body %}
    <header>
        <h1>What is a Pebble Bed Reactor?</h1>
    </header>
    <article>
        <p>The pebble-bed reactor (PBR) is a graphite-moderated, gas-cooled nuclear reactor. 
		It is a type of very-high-temperature reactor (VHTR), one of the six classes of nuclear reactors in the Generation IV initiative. 
		The basic design of pebble-bed reactors features spherical fuel elements called pebbles. 
		These tennis ball-sized pebbles are made of pyrolytic graphite (which acts as the moderator), 
		and they contain thousands of micro-fuel particles called TRISO particles. 
		These TRISO fuel particles consist of a fissile material (such as 235U) surrounded by a coated ceramic layer of silicon carbide 
		for structural integrity and fission product containment. In the PBR, thousands of pebbles are amassed to create a reactor core, 
		and are cooled by a gas, such as helium, nitrogen or carbon dioxide, that does not react chemically with the fuel elements.
        </n>
        This type of reactor is claimed to be passively safe; that is, it removes the need for redundant, active safety systems. 
		Because the reactor is designed to handle high temperatures, it can cool by natural circulation and still survive in accident scenarios, 
		which may raise the temperature of the reactor to 1,600 °C. 
		Because of its design, its high temperatures allow higher thermal efficiencies than possible in traditional nuclear power plants (up to 50%) 
		and has the additional feature that the gases do not dissolve contaminants or absorb neutrons as water does, 
		so the core has less in the way of radioactive fluids.
        </n>
        The concept was first suggested by Farrington Daniels in the 1940s, s
		aid to have been inspired by the innovative design of the benghazi burner by British desert troops in WWII, 
		but commercial development did not take place until the 1960s in the German AVR reactor by Rudolf Schulten. 
		but this system was plagued with problems and political and economic decisions were made to abandon the technology.
		The AVR design was licensed to South Africa as the PBMR and China as the HTR-10, the latter currently the only such design operational. 
		In various forms, other designs are under development by MIT, University of California at Berkeley, General Atomics (U.S.), 
		the Dutch company Romawa B.V., Adams Atomic Engines, and Idaho National Laboratory.
		</p>
</n>
<p>(Source: https://en.wikipedia.org/wiki/Pebble-bed_reactor)</p>
    </article>
{% endblock %}

pbrworld.dev/src/BlogBundle/Resources/views/Page/contact.html.twig
{% extends 'BlogBundle::layout.html.twig' %}

{% block title %}Contact{% endblock%}

{% block body %}
    <header>
        <h1>Contact PBR World</h1>
    </header>
	
	{% for flashMessage in app.session.flashbag.get('blogger-notice') %}
		<div class="blogger-notice">
			{{ flashMessage }}
		</div>
	{% endfor %}

    <p>Want to contact PBR World?</p>
	
	<form action="{{ path('BlogBundle_contact') }}" method="post" {{ form_enctype(form) }} class="blogger">
        {{ form_errors(form) }}

        {{ form_row(form.name) }}
        {{ form_row(form.email) }}
        {{ form_row(form.subject) }}
        {{ form_row(form.body) }}

        {{ form_rest(form) }}

        <input type="submit" value="Submit" />
    </form>
{% endblock %}

pbrworld.dev/src/BlogBundle/Resources/views/Page/contactEmail.txt.twig
A contact enquiry was made by {{ enquiry.name }} at {{ "now" | date("Y-m-d H:i") }}.

Reply-To: {{ enquiry.email }}
Subject: {{ enquiry.subject }}
Body:
{{ enquiry.body }}

pbrworld.dev/src/BlogBundle/Resources/views/Page/index.html.twig
{% extends 'BlogBundle::layout.html.twig' %}

{% block body %}
    {% for blog in blogs %}
        <article class="blog">
            <div class="date"><time datetime="{{ blog.created|date('c') }}">{{ blog.created|date('l, F j, Y') }}</time></div>
            <header>
                <h2><a href="{{ path('BlogBundle_blog_show', { 'id': blog.id, 'slug': blog.slug }) }}">{{ blog.title }}</a></h2>
            </header>

            <img src="{{ asset(['images/', blog.image]|join) }}" />
            <div class="snippet">
                <p>{{ blog.blog(500) }}</p>
                <p class="continue"><a href="{{ path('BlogBundle_blog_show', { 'id': blog.id, 'slug': blog.slug }) }}">Continue reading...</a></p>
            </div>

            <footer class="meta">
                <p>Comments: <a href="{{ path('BlogBundle_blog_show', { 'id': blog.id, 'slug': blog.slug }) }}#comments">{{ blog.comments|length }}</a></p>
                <p>Posted by <span class="highlight">{{ blog.author }}</span> at {{ blog.created|date('h:iA') }}</p>
                <p>Tags: <span class="highlight">{{ blog.tags }}</span></p>
            </footer>
        </article>
    {% else %}
        <p>There are no blog entries for PBR World</p>
    {% endfor %}
{% endblock %}

pbrworld.dev/src/BlogBundle/Resources/views/Page/sidebar.html.twig
<section class="section">
    <header>
        <h3>Tag Cloud</h3>
    </header>
    <p class="tags">
        {% for tag, weight in tags %}
            <span class="weight-{{ weight }}">{{ tag }}</span>
        {% else %}
            <p>There are no tags</p>
        {% endfor %}
    </p>
</section>

<section class="section">
    <header>
        <h3>Latest Comments</h3>
    </header>
    {% for comment in latestComments %}
        <article class="comment">
            <header>
                <p class="small"><span class="highlight">{{ comment.user }}</span> commented on
                    <a href="{{ path('BlogBundle_blog_show', { 'id': comment.blog.id, 'slug': comment.blog.slug }) }}#comment-{{ comment.id }}">
    					{{ comment.blog.title }}
					</a>
                    <em><time datetime="{{ comment.created|date('c') }}">{{ comment.created|created_ago }}</time></em>
                </p>
            </header>
            <p>{{ comment.comment }}</p>
            </p>
        </article>
    {% else %}
        <p>There are no comments for this post. Be the first to comment...</p>
    {% endfor %}
</section>